openapi: 3.0.0
info:
  contact:
    name: Mackyson
  description: HaiqueのもろもろのAPI
  license:
    name: MIT
  title: Haique
  version: "1.0"
servers:
- description: localhost
  url: http://localhost:8080
paths:
  /api/signup:
    post:
      description: サインアップ
      operationId: post-signup
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                pw:
                  type: string
              required:
              - name
              - pw
              type: object
      responses:
        "201":
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/inline_response_201'
          description: Created
        "409":
          description: Conflict
  /api/signin:
    post:
      description: ログイン
      operationId: post-signin
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/inline_object_1'
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                pw:
                  type: string
              required:
              - name
              - pw
              type: object
      responses:
        "200":
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/inline_response_201'
            application/xml:
              schema:
                $ref: '#/components/schemas/inline_response_201'
          description: OK
        "400":
          description: Bad Request
  /api/post-haiku:
    post:
      description: 詠む
      operationId: post-haiku
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/inline_object_2'
        content:
          application/json:
            examples: {}
            schema:
              properties:
                session_id:
                  format: uuid
                  type: string
                content:
                  $ref: '#/components/schemas/_api_post_haiku_content'
              required:
              - content
              - session_id
              type: object
              x-examples:
                example-1:
                  content:
                    first: using
                    second: namespace
                    third: std
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
  /api/subscribe/{user_id}:
    delete:
      description: リムーブ
      operationId: delete-subscribe
      parameters:
      - explode: false
        in: path
        name: user_id
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/inline_object_4'
        content:
          application/json:
            schema:
              properties:
                session_id:
                  format: uuid
                  type: string
              required:
              - session_id
              type: object
              x-examples:
                example-1:
                  session_id: hoge
      responses:
        "200":
          description: OK
    post:
      description: フォロー
      operationId: post-subscribe
      parameters:
      - explode: false
        in: path
        name: user_id
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/inline_object_3'
        content:
          application/json:
            schema:
              properties:
                session_id:
                  format: uuid
                  type: string
              required:
              - session_id
              type: object
              x-examples:
                example-1:
                  session_id: hoge
      responses:
        "200":
          description: OK
  /api/top:
    get:
      description: トップ30件のhaikuの取得
      operationId: get-top
      parameters: []
      responses:
        "200":
          content:
            application/json:
              examples:
                example-1:
                  value:
                  - haiku_id: 0
                    author_id: 0
                    content:
                      first: string
                      second: string
                      third: string
                      author_name: string
                    likes: 0
                    created_at: 0
              schema:
                items:
                  $ref: '#/components/schemas/Haiku'
                type: array
          description: OK
      summary: top
      tags: []
  /api/timeline:
    get:
      description: タイムラインの取得
      operationId: get-timeline
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/inline_object_5'
        content:
          application/json:
            schema:
              properties:
                session_id:
                  format: uuid
                  type: string
              required:
              - session_id
              type: object
              x-examples:
                example-1:
                  session_id: hoge
          application/xml:
            schema:
              properties:
                start:
                  description: timelineのN番目のhaikuを起点とする
                  type: integer
                end:
                  description: M番目を終点とする
                  type: integer
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                description: タイムラインでの俳句表示は名前以外のUser情報を載せない
                items:
                  $ref: '#/components/schemas/Haiku'
                type: array
          description: OK
      summary: timeline
      tags: []
  /api/users/{user_id}:
    get:
      description: ユーザー情報
      operationId: get-user
      parameters:
      - explode: false
        in: path
        name: user_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: OK
      summary: user_info
      tags: []
  /api/{haiku_id}:
    delete:
      description: haikuを削除
      operationId: delete-haiku
      parameters:
      - explode: false
        in: path
        name: haiku_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/inline_object_6'
        content:
          application/json:
            schema:
              properties:
                session_id:
                  format: uuid
                  type: string
              required:
              - session_id
              type: object
              x-examples:
                example-1:
                  session_id: hoge
      responses:
        "200":
          description: OK
    get:
      description: haikuの詳細を取得
      operationId: get-haiku
      parameters:
      - explode: false
        in: path
        name: haiku_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
          description: OK
      summary: get_haiku
      tags: []
components:
  requestBodies:
    inline_object_1:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_1'
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
    inline_object_6:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_6'
    inline_object_5:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_5'
        application/xml:
          schema:
            $ref: '#/components/schemas/inline_object_5'
    inline_object_4:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_4'
    inline_object_3:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_3'
    inline_object_2:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_2'
  schemas:
    User:
      example:
        user_id: 0
        timeline_haiku_id_list:
        - 5
        - 5
        subscribed_by:
        - 1
        - 1
        name: name
        author_haiku_id_list:
        - 5
        - 5
        subscription:
        - 6
        - 6
      properties:
        user_id:
          format: int64
          type: integer
        name:
          type: string
        subscription:
          items:
            format: int64
            type: integer
          type: array
        subscribed_by:
          items:
            format: int64
            type: integer
          type: array
        author_haiku_id_list:
          items:
            format: int64
            type: integer
          type: array
        timeline_haiku_id_list:
          items:
            format: int64
            type: integer
          type: array
      required:
      - author_haiku_id_list
      - name
      - subscribed_by
      - subscription
      - timeline_haiku_id_list
      - user_id
      type: object
      x-examples:
        example-1:
          user_id: 1
          name: hoge
          subscription:
          - 1
          - 2
          - 3
          subscribed_by:
          - 1
          - 2
          - 3
          posts:
          - 1
          - 2
          - 3
    Haiku:
      example:
        created_at: 5
        author_id: 6
        haiku_id: 0
        content:
          author_name: author_name
          third: third
          first: first
          second: second
        likes: 1
      properties:
        haiku_id:
          format: int64
          type: integer
        author_id:
          format: int64
          type: integer
        content:
          $ref: '#/components/schemas/Haiku_content'
        likes:
          type: integer
        created_at:
          description: unixtime
          format: int64
          type: integer
      required:
      - author_id
      - content
      - created_at
      - haiku_id
      - likes
      type: object
      x-examples:
        example-1:
          haiku_id: -9223372036854776000
          author:
            user_id: 1
            user_name: hoge
          content:
            first: string
            second: string
            third: string
          likes: 0
          created_at: 2019-08-24T14:15:22Z
    inline_object:
      properties:
        name:
          type: string
        pw:
          type: string
      required:
      - name
      - pw
      type: object
    inline_response_201:
      example:
        session_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        session_id:
          format: uuid
          type: string
      required:
      - session_id
      type: object
      x-examples:
        example-1:
          session_id: hoge
    inline_object_1:
      properties:
        name:
          type: string
        pw:
          type: string
      required:
      - name
      - pw
      type: object
    _api_post_haiku_content:
      properties:
        first:
          minLength: 1
          type: string
        second:
          minLength: 1
          type: string
        third:
          minLength: 1
          type: string
      required:
      - first
      - second
      - third
      type: object
    inline_object_2:
      properties:
        session_id:
          format: uuid
          type: string
        content:
          $ref: '#/components/schemas/_api_post_haiku_content'
      required:
      - content
      - session_id
      type: object
      x-examples:
        example-1:
          content:
            first: using
            second: namespace
            third: std
    inline_object_3:
      properties:
        session_id:
          format: uuid
          type: string
      required:
      - session_id
      type: object
      x-examples:
        example-1:
          session_id: hoge
    inline_object_4:
      properties:
        session_id:
          format: uuid
          type: string
      required:
      - session_id
      type: object
      x-examples:
        example-1:
          session_id: hoge
    inline_object_5:
      properties:
        session_id:
          format: uuid
          type: string
      required:
      - session_id
      type: object
      x-examples:
        example-1:
          session_id: hoge
    inline_response_200:
      properties:
        user:
          $ref: '#/components/schemas/User'
        haikus:
          items:
            $ref: '#/components/schemas/Haiku'
          type: array
      required:
      - haikus
      - user
      type: object
    inline_response_200_1:
      example:
        author:
          user_id: 0
          timeline_haiku_id_list:
          - 5
          - 5
          subscribed_by:
          - 1
          - 1
          name: name
          author_haiku_id_list:
          - 5
          - 5
          subscription:
          - 6
          - 6
        haiku:
          created_at: 5
          author_id: 6
          haiku_id: 0
          content:
            author_name: author_name
            third: third
            first: first
            second: second
          likes: 1
      properties:
        author:
          $ref: '#/components/schemas/User'
        haiku:
          $ref: '#/components/schemas/Haiku'
      type: object
    inline_object_6:
      properties:
        session_id:
          format: uuid
          type: string
      required:
      - session_id
      type: object
      x-examples:
        example-1:
          session_id: hoge
    Haiku_content:
      example:
        author_name: author_name
        third: third
        first: first
        second: second
      properties:
        first:
          minLength: 1
          type: string
        second:
          minLength: 1
          type: string
        third:
          minLength: 1
          type: string
        author_name:
          type: string
      required:
      - author_name
      - first
      - second
      - third
      type: object
